@startuml
left to right direction
skinparam packgestyle rectangle
actor Professor
rectangle "gerenciar departamentos" {
  Professor -- (adicionar departamento)
  Professor -- (excluir departamento)
  Professor -- (editar departamento)
  (excluir departamento) ..> (selecionar departamento): <<include>>
  (editar departamento) ..> (selecionar departamento): <<include>>
}
@enduml