@startuml
actor Usuario
boundary "tela de login" as login
control LogController as controle
entity AdminEntity as entidade

Usuario ->> login: tentar acessar a conta
activate login
login ->> controle: requisitar Autenticação
activate controle

controle -> entidade: buscar admin
    activate entidade
    alt Usuario existe na base de dados
        
        entidade --> controle: admin encontrado
        'deactivate controle
         controle -> controle: verificar dados do admin
        alt dados válidos
            controle -->> login: admin Autenticado
            login --> Usuario: acesso permitido 
        else dados inválidos
            
            login <<-- controle: não Autenticado
            login --> Usuario: acesso não permitido
        end
       
    else Usuario não cadastrado
        
        entidade --> Usuario: admin não encontrado
        deactivate entidade
end
@enduml