@startuml
actor Aluno
boundary "Tela de login" as login
control  loginController
entity StudentEntity

Aluno ->> login: Solicitar acesso a conta
activate login
login ->> loginController: Requisitar Autenticação
activate loginController

loginController -> StudentEntity: Buscar aluno
    activate StudentEntity
    alt Professor existe na base de dados
        
        StudentEntity --> loginController: aluno encontrado
        'deactivate loginController
         loginController -> loginController: Verificar dados do aluno
        alt dados válidos
            loginController -->> login: Aluno Autenticado
            login -->> Aluno: Acesso permitido 
        else dados inválidos
            
            login <<-- loginController: Não Autenticado
            login -->> Aluno: Acesso não permitido
        end
       
    else Aluno não cadastrado
        
        StudentEntity --> Aluno: aluno não encontrado
        deactivate StudentEntity
end

@enduml