@startuml
actor Professor
boundary "tela de grupos" as grupo
control GroupController
entity GroupEntity

Professor ->> grupo: tentar deletar um grupo
activate Professor
activate grupo
grupo ->> GroupController: solicitar exclusão do grupo
deactivate grupo
activate GroupController
GroupController -> GroupEntity: confirmar exclusão de grupo
activate GroupEntity
deactivate GroupController
GroupEntity --> GroupController: mensagem de confirmação
deactivate GroupEntity
activate GroupController
GroupController -->> grupo: enviar mensagem de confirmação
deactivate GroupController
activate grupo
grupo -->> Professor: exibir mensagem de confirmação
deactivate grupo
@enduml