@startuml
actor Professor

boundary "tela de grupos" as grupo
control ItemController
entity ItemEntity

Professor ->> grupo: tentar alterar um item
activate Professor
activate grupo
grupo ->> ItemController: solicitar alteração do item
deactivate grupo
activate ItemController
ItemController -> ItemEntity: confirmar alteração do item
deactivate ItemController
activate ItemEntity
ItemEntity --> ItemController: mensagem de confirmação
deactivate ItemEntity
activate ItemController
ItemController -->> grupo: enviar mensagem de confirmação
deactivate ItemController
activate grupo
grupo -->> Professor: exibir mensagem de confirmação
deactivate grupo
@enduml