@startuml
actor Professor
boundary "tela de cadastro de professor" as cadastro
control ProfessorController
entity ProfessorEntity

Professor -> cadastro: entrar com os dados do professor
activate Professor
activate cadastro
cadastro ->o UTFPR: verificar se o professor pertence a UTFPR-CP
activate UTFPR
deactivate cadastro
alt Professor pertence a UTFPR-CP
    UTFPR o--> cadastro: professor pertence
    activate cadastro
    cadastro --> Professor: mensagem de sucesso
    deactivate Professor
    deactivate cadastro
    Professor ->> cadastro: confirmar envio de dados
    activate Professor
    activate cadastro
    cadastro ->> ProfessorController: requisitar cadastro de professor
    deactivate cadastro
    activate ProfessorController
    ProfessorController -> ProfessorEntity: salvar professor
    activate ProfessorEntity
    deactivate ProfessorController
    ProfessorEntity --> ProfessorController: salvado
    deactivate ProfessorEntity
    activate ProfessorController
    ProfessorController -->> cadastro: responder com mesagem de 'ok'
    deactivate ProfessorController
    activate cadastro
    cadastro -->> Professor: salvo com sucesso
    deactivate Professor
    deactivate cadastro 
else Professor não pertence
    UTFPR o--> cadastro: professor não pertence
    activate cadastro
    cadastro --> Professor: cadastro não permitido
    deactivate cadastro
    activate Professor
end     
@enduml